version: '3.1'

services:
  newman:
    image: postman/newman:alpine
    restart: on-failure
    command:
        run -t postman/newman:alpine run "https://www.getpostman.com/collections/f8d7e82fd742f91a2dad" --reporters="junit,cli" --reporter-junit-export="newman-report.xml"