version: '3.1'

services:
  newman:
    image: postman/newman:alpine
    command:
        run "DevOpsTest.postman_collection.json"
        --environment="EnviromentDevOpTest.postman_environment.json" 
        --reporters="cli,json,junit"
        --reporter-json-export="devOps-results.json"
    volumes:
      - /W/DevOps/trabajo-final/app/src/main/resources/postman:/etc/newman