version: '3.1'

services:
  api:
    image: wyataco/prueba-api:1.0.2
    restart: always
    networks:
      - apinet
    ports:
      - 5000:5000
    environment:
      APP_PORT: 5000
      SWAGGER_HOST: 127.0.0.1
            
networks:
  apinet:
    driver: bridge